### ISSUE TITLE
Error when was executing the ".py" file

### ISSUE THREAD

**Issue by masuta16** [ethankruse/kepler_orrery#1]
File "orrery.py", line 212
    print 'Placing {0} of {1} planets'.format(ii, nplan)
                                     ^
SyntaxError: invalid syntax

**Comment by ethankruse** [comment]
Yeah, this was done in Python 2.7. I haven't upgraded anything to Python 3 yet so there will be some compatibility issues like this.

**Comment by masuta16** [comment]
So please let this information in README file
